// Generated by CoffeeScript 1.7.1
(function() {
  var Client, Http, Server, express, gimmeEnv, helpers, port, v, validator;

  validator = require('validator2-extras');

  v = validator.v;

  Server = require('./transports/server/websocket');

  Client = require('./transports/client/websocket');

  helpers = require('helpers');

  express = require('express');

  Http = require('http');

  port = 8192;

  gimmeEnv = function(callback) {
    var app, http, lwebc, lwebs;
    app = express();
    app.configure(function() {
      app.set('view engine', 'ejs');
      app.use(express.favicon());
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.cookieParser());
      app.use(app.router);
      return app.use(function(err, req, res, next) {
        return res.send(500, 'BOOOM!');
      });
    });
    http = Http.createServer(app);
    http.listen(++port);
    lwebs = new Server.webSocketServer({
      http: http
    });
    lwebc = new Client.webSocketClient({
      host: 'http://localhost:' + port
    });
    return lwebs.on('connect', function(s) {
      return callback(lwebs, s, lwebc, function(test) {
        return lwebs.stop(function() {
          return lwebc.stop(function() {
            return test.done();
          });
        });
      });
    });
  };

  exports.init = function(test) {
    return gimmeEnv(function() {
      return test.done();
    });
  };

  exports.ClientSend = function(test) {
    return gimmeEnv(function(lwebs, s, c, done) {
      s.subscribe({
        test: true
      }, function(msg) {
        return done(test);
      });
      return c.send({
        test: 1
      });
    });
  };

  exports.ServerSend = function(test) {
    return gimmeEnv(function(lwebs, s, c, done) {
      c.subscribe({
        test: true
      }, function(msg) {
        return done(test);
      });
      return s.send({
        test: 1
      });
    });
  };

  exports.QueryProtocol = function(test) {
    var query;
    query = require('protocol/query');
    return gimmeEnv(function(lwebs, s, c, done) {
      var total;
      s.addProtocol(query.server);
      c.addProtocol(query.client);
      s.query.subscribe({
        test: Number
      }, function(msg, reply) {
        reply.write({
          reply: msg.test + 3
        });
        return reply.end({
          reply: msg.test + 2
        });
      });
      total = 0;
      return c.query.send({
        test: 7
      }, function(msg, end) {
        total += msg.reply;
        if (end) {
          test.equal(total, 19);
          return test.done();
        }
      });
    });
  };

  exports.ChannelProtocol = function(test) {
    var channel, query;
    query = require('protocol/query');
    channel = require('protocol/channel');
    return gimmeEnv(function(lwebs, s, c, done) {
      s.addProtocol(new channel.server());
      c.addProtocol(new channel.client());
      return c.subscribe('testchannel', function(err, channel) {
        if (err) {
          return test.fail();
        }
        test.equal(channel, c.channel.testchannel);
        channel.subscribe({
          test: 1
        }, function(msg) {
          test.equals(msg.bla, 3);
          return channel.unsubscribe(function(err, data) {
            if (err) {
              return test.fail();
            }
            s.channel.testchannel.broadcast({
              test: 2,
              bla: 4
            });
            return helpers.wait(100, function() {
              return done(test);
            });
          });
        });
        return s.channel.testchannel.broadcast({
          test: 1,
          bla: 3
        });
      });
    });
  };

}).call(this);
