// Generated by CoffeeScript 1.7.1
(function() {
  var Client, Http, Server, express, gimmeEnv, helpers, port, v, validator;

  validator = require('validator2-extras');

  v = validator.v;

  Server = require('./transports/server/websocket');

  Client = require('./transports/client/websocket');

  helpers = require('helpers');

  express = require('express');

  Http = require('http');

  port = 8192;

  gimmeEnv = function(callback) {
    var app, http, lwebc, lwebs;
    app = express();
    app.configure(function() {
      app.set('view engine', 'ejs');
      app.use(express.favicon());
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.cookieParser());
      app.use(app.router);
      return app.use(function(err, req, res, next) {
        return res.send(500, 'BOOOM!');
      });
    });
    http = Http.createServer(app);
    http.listen(++port);
    lwebs = new Server.webSocketServer({
      http: http
    });
    lwebc = new Client.webSocketClient({
      host: 'http://localhost:' + port
    });
    return lwebs.on('connect', function(s) {
      return callback(lwebs, s, lwebc, function(test) {
        return lwebs.stop(function() {
          return lwebc.stop(function() {
            return test.done();
          });
        });
      });
    });
  };

  exports.init = function(test) {
    return gimmeEnv(function() {
      return test.done();
    });
  };

  exports.ClientSend = function(test) {
    return gimmeEnv(function(lwebs, s, c, done) {
      s.subscribe({
        test: true
      }, function(msg) {
        return done(test);
      });
      return c.send({
        test: 1
      });
    });
  };

  exports.ServerSend = function(test) {
    return gimmeEnv(function(lwebs, s, c, done) {
      c.subscribe({
        test: true
      }, function(msg) {
        return done(test);
      });
      return s.send({
        test: 1
      });
    });
  };

}).call(this);
