// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, channelInterface, client, clientChannel, core, helpers, query, server, serverChannel, subscriptionMan, v, validator, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  core = require('../core');

  query = require('./query');

  channelInterface = core.protocol.extend4000({
    initialize: function() {
      return this.channels = {};
    },
    channel: function(channelname) {
      var channel;
      if (channel = this.channels[channelname]) {
        return channel;
      }
      channel = this.channels[channelname] = new this.channelClass({
        parent: this,
        name: channelname
      });
      channel.once('del', (function(_this) {
        return function() {
          return delete _this.channels[channelname];
        };
      })(this));
      return channel;
    },
    channelsubscribe: function(channelname, pattern, callback) {
      var channel;
      channel = this.channel(channelname);
      if (!callback && pattern.constructor === Function) {
        callback = pattern;
        pattern = true;
      }
      return channel.subscribe(pattern, callback);
    },
    broadcast: function(channel, message) {
      return true;
    },
    join: function(name, pattern, callback) {
      return this.channel('name').join(pattern, callback);
    },
    part: function(channel, listener) {
      return true;
    },
    del: function() {
      return true;
    }
  });

  clientChannel = core.core.extend4000({
    name: 'channelClient',
    initialize: function() {
      return this.name = this.get('name');
    },
    join: function(pattern, callback) {
      var msg;
      if (!callback) {
        callback = pattern;
        pattern = void 0;
      }
      if (this.joined) {
        return;
      } else {
        this.joined = true;
      }
      msg = {
        join: this.name
      };
      if (pattern) {
        msg.pattern = pattern;
      }
      this.query = this.parent.parent.queryClient.send(msg, (function(_this) {
        return function(msg) {
          return _this.event(msg.payload);
        };
      })(this));
      if (callback) {
        return this.subscribe(true, callback);
      }
    },
    part: function() {
      this.joined = false;
      return this.query.cancel();
    }
  });

  client = exports.client = channelInterface.extend4000({
    name: 'channelClient',
    requires: [query.client],
    channelClass: clientChannel
  });

  serverChannel = core.core.extend4000({
    initialize: function() {
      this.name = this.get('name');
      return this.clients = [];
    },
    join: function(reply, pattern) {
      return this.subscribe(pattern || true, function(msg) {
        return reply.write(msg);
      });
    },
    part: function(reply) {
      return true;
    },
    broadcast: function(msg) {
      return this.event(msg);
    },
    end: function(msg) {
      _.map(this.clients, function(client) {
        return client.end(msg);
      });
      this.clients = [];
      return this.trigger('end');
    }
  });

  server = exports.server = channelInterface.extend4000({
    name: 'channelServer',
    requires: [query.server],
    channelClass: serverChannel,
    initialize: function() {
      return this.when('parent', (function(_this) {
        return function(parent) {
          return parent.queryServer.subscribe({
            join: String
          }, function(msg, reply) {
            return _this.channel(msg.join).join(reply, msg.pattern);
          });
        };
      })(this));
    }
  });

}).call(this);
