// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, core, helpers, io, subscriptionMan, v, validator, webSocketServer, websocket, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  io = require('socket.io');

  core = require('../../core');

  _.extend(exports, websocket = require('./websocket'));

  webSocketServer = core.server.extend4000(validator.ValidatedModel, {
    validator: {
      http: 'Instance',
      channelClass: 'Function'
    },
    initialize: function() {
      var channelClass, http;
      http = this.get('http');
      channelClass = webSocketChannel.extend4000(this.get('channelClass'));
      this.socketIo = io.listen(http, {
        log: false
      });
      return this.socketIo.on('conection', (function(_this) {
        return function(socketIoClient) {
          return _this.trigger('connect', new channelClass({
            socketIo: socketIoClient
          }));
        };
      })(this));
    }
  });

}).call(this);
