// Generated by CoffeeScript 1.8.0
(function() {
  var Backbone, helpers, nssocket, nssocketClient, subscriptionMan, v, validator, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  nssocket = require('nssocket');

  _.extend(exports, require('../nssocket'));

  nssocketClient = exports.nssocketClient = exports.nssocketChannel.extend4000({
    defaults: {
      name: 'nssocketClient'
    },
    initialize: function() {
      this.set({
        nssocket: this.nssocket = nssocket.NsSocket({
          reconnect: true,
          type: 'tcp4'
        })
      });
      console.log('calling connect', this.get('host'), this.get('port'));
      return this.nssocket.connect(this.get('host'), this.get('port'));
    },
    end: function() {
      return this.nssocket.disconnect();
    }
  });

}).call(this);
