// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, helpers, io, subscriptionMan, v, validator, webSocketClient, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  io = require('socket.io-browserify');

  _.extend(exports, require('../websocket'));

  webSocketClient = exports.webSocketClient = exports.webSocketChannel.extend4000({
    initialize: function() {
      return this.socketIo = io.connect(this.get('host') || "http://" + (typeof window === "function" ? window(typeof location === "function" ? location(host) : void 0) : void 0));
    },
    stop: function(cb) {
      this.socketIo.disconnect();
      return cb();
    }
  });

}).call(this);
