// Generated by CoffeeScript 1.8.0
(function() {
  var Backbone, core, helpers, subscriptionMan, tcpSocketChannel, v, validator, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  core = require('../core');

  tcpSocketChannel = exports.tcpSocketChannel = core.channel.extend4000({
    defaults: {
      name: 'tcp'
    },
    initialize: function() {
      var realm;
      realm = {
        client: this
      };
      this.when('socket', (function(_this) {
        return function(socket) {
          _this.socket = socket;
          _this.socket.on('data', function(msg) {
            msg = String(msg);
            _this.log("<", msg);
            return _this.event(msg, realm);
          });
          _this.socket.on('connect', function() {
            return _this.trigger('connect');
          });
          return _this.socket.on('end', function() {
            return _this.trigger('disconnect');
          });
        };
      })(this));
      return this.when('parent', (function(_this) {
        return function(parent) {
          return _this.socket.on('data', function(msg) {
            msg = String(msg);
            return parent.event(msg, realm);
          });
        };
      })(this));
    },
    send: function(msg) {
      this.log(">", msg);
      return this.socket.write(msg);
    }
  });

}).call(this);
