// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, core, helpers, io, subscriptionMan, v, validator, webSocketChannel, _;

  _ = require('underscore');

  Backbone = require('backbone4000');

  helpers = require('helpers');

  subscriptionMan = require('subscriptionman2');

  validator = require('validator2-extras');

  v = validator.v;

  io = require('socket.io');

  core = require('../core');

  webSocketChannel = exports.webSocketChannel = core.channel.extend4000({
    initialize: function() {
      return this.when('socketIo', (function(_this) {
        return function(socketIo) {
          _this.socketIo = socketIo;
          return _this.socketIo.on('msg', function(msg) {
            console.log("<", msg);
            return _this.event(msg);
          });
        };
      })(this));
    },
    send: function(msg) {
      console.log(">", msg);
      return this.socketIo.emit('msg', msg);
    },
    receive: function(pattern, callback) {
      return this.socketIo.on('msg', callback);
    }
  });

}).call(this);
